# Site settings
title: Malaubid
email: your-email@domain.com
description: The plain text recipe database for hackers
baseurl: "http://malau.bid"
twitter_username: libussa
github_username:  libussa

# Build settings
markdown: kramdown

collections:
  components:
    output: true
  recipes:
    output: true

gems: ['jekyll-lunr-js-search']
    
mini_magick:
    thumbnail:
        source: images/_original
        destination: images/thumbnail
        resize: "400x400"
    medium:
        source: images/_original
        destination: images/medium
        resize: "1200x1200"
    large:
        source: images/_original
        destination: images/large
        resize: "2000x2000"

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
