# Site settings
title: Malaubid
email: your-email@domain.com
description: The plain text recipe database for hackers
# use this if you're using a /folder
baseurl: ""
url: "https://malau.bid"
twitter_username: libussa
github_username:  libussa

# Build settings
markdown: kramdown

collections:
  components:
    output: true
  recipes:
    output: true

gems: ['jekyll-lunr-js-search']
    
mini_magick:
    thumbnail:
        source: _recipes
        destination: images/thumbnail
        resize: "400x400"
    medium:
        source: _recipes
        destination: images/medium
        resize: "800x800"
    large:
        source: _recipes
        destination: images/large
        resize: "1500x1500"

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
